#!/usr/bin/env python3

import sys
import subprocess
import json

sys.argv.reverse()
sys.argv.pop()
if ("--help" in sys.argv):
    print("""
nix-check: a simple tool to run all checks for a nix flake
usage: nix-check
    """)
    exit(0)

system = subprocess.check_output([
    "nix",
    "eval",
    "--impure",
    "--raw",
    "--expr",
    "builtins.currentSystem"
]).decode("utf-8")
flake = json.loads(subprocess.check_output(["nix", "flake", "show", "--json"]))
checks = dict.keys(flake["checks"][system])
checkSelectors = [f".#checks.{system}.{check}" for check in checks]
print("Running the following checks:")
for selector in checkSelectors:
    print(selector)
for selector in checkSelectors:
    print(f"Running {selector}...")
    result = subprocess.run(["nix", "-L", "build", selector])
    if (result.returncode != 0):
        print(f"{selector} failed!")
        exit(result.returncode)
